name: CPU Test

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

  schedule:
    # Every day at noon and midnight
    - cron: '0 0,12 * * *'

jobs:
  test-pat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create test branch
        run: |
          echo "test $(date)" > test.txt
          git config user.name "agent-lightning-bot"
          git config user.email "agent-lightning-bot@github.com"
          git add test.txt
          git commit -m "Test commit for PAT"
          git branch -M test-pat-branch
          git remote add origin https://github.com/${{ github.repository }}.git
          git push --force "https://${{ secrets.BOT_PAT }}@github.com/${{ github.repository }}" HEAD:test-pat-branch

      - name: Attempt to open PR with PAT
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.BOT_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{"title":"Test PR from PAT","head":"test-pat-branch","base":"main","body":"This is a test PR created via PAT."}'
